export type AdminTaskStatus = 'Completada' | 'En Progreso' | 'Backlog'

export type AdminTaskItem = {
  id: string
  title: string
  description: string
  group: string
  groupAccent: 'red' | 'orange' | 'green' | 'blue'
  assignee: string
  assigneeInitials: string
  status: AdminTaskStatus
  estimatedHours: string
  createdAt: string
  completedAt?: string
  actualHours?: string
}

export const adminTasks: AdminTaskItem[] = [
  {
    id: 'task-1',
    title: 'Refactorizar codigo legacy',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Frank Miller',
    assigneeInitials: 'FM',
    status: 'En Progreso',
    estimatedHours: '15h',
    createdAt: '2026-03-22',
  },
  {
    id: 'task-2',
    title: 'Crear componentes reutilizables',
    description: 'Descripcion de la tarea',
    group: 'DevOps Team',
    groupAccent: 'orange',
    assignee: 'Henry Moore',
    assigneeInitials: 'HM',
    status: 'Completada',
    estimatedHours: '8h',
    createdAt: '2026-03-22',
    completedAt: '2026-03-22',
    actualHours: '8h',
  },
  {
    id: 'task-3',
    title: 'Crear landing page',
    description: 'Descripcion de la tarea',
    group: 'DevOps Team',
    groupAccent: 'orange',
    assignee: 'Grace Wilson',
    assigneeInitials: 'GW',
    status: 'En Progreso',
    estimatedHours: '8h',
    createdAt: '2026-03-21',
  },
  {
    id: 'task-4',
    title: 'Refactorizar codigo legacy',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Emma Davis',
    assigneeInitials: 'ED',
    status: 'En Progreso',
    estimatedHours: '5h',
    createdAt: '2026-03-19',
  },
  {
    id: 'task-5',
    title: 'Diseñar sistema de permisos',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Frank Miller',
    assigneeInitials: 'FM',
    status: 'En Progreso',
    estimatedHours: '6h',
    createdAt: '2026-03-18',
  },
  {
    id: 'task-6',
    title: 'Documentar API REST',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Bob Smith',
    assigneeInitials: 'BS',
    status: 'Completada',
    estimatedHours: '10h',
    createdAt: '2026-03-17',
    completedAt: '2026-03-21',
    actualHours: '13h',
  },
  {
    id: 'task-7',
    title: 'Diseñar sistema de permisos',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'Carol White',
    assigneeInitials: 'CW',
    status: 'Completada',
    estimatedHours: '13h',
    createdAt: '2026-03-17',
    completedAt: '2026-03-19',
    actualHours: '16h',
  },
  {
    id: 'task-8',
    title: 'Implementar sistema de notificaciones',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Bob Smith',
    assigneeInitials: 'BS',
    status: 'En Progreso',
    estimatedHours: '10h',
    createdAt: '2026-03-16',
  },
  {
    id: 'task-9',
    title: 'Diseñar dashboard de usuario',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Emma Davis',
    assigneeInitials: 'ED',
    status: 'Completada',
    estimatedHours: '17h',
    createdAt: '2026-03-16',
    completedAt: '2026-03-16',
    actualHours: '17h',
  },
  {
    id: 'task-10',
    title: 'Integrar sistema de pagos',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'Backlog',
    estimatedHours: '11h',
    createdAt: '2026-03-16',
  },
  {
    id: 'task-11',
    title: 'Realizar pruebas de integración',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'Completada',
    estimatedHours: '10h',
    createdAt: '2026-03-15',
    completedAt: '2026-03-15',
    actualHours: '10h',
  },
  {
    id: 'task-12',
    title: 'Mejorar rendimiento del frontend',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'En Progreso',
    estimatedHours: '7h',
    createdAt: '2026-03-15',
  },
  {
    id: 'task-13',
    title: 'Realizar pruebas de integración',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Emma Davis',
    assigneeInitials: 'ED',
    status: 'Completada',
    estimatedHours: '13h',
    createdAt: '2026-03-15',
    completedAt: '2026-03-15',
    actualHours: '12h',
  },
  {
    id: 'task-14',
    title: 'Configurar pipeline de CI/CD',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Alice Johnson',
    assigneeInitials: 'AJ',
    status: 'Backlog',
    estimatedHours: '5h',
    createdAt: '2026-03-12',
  },
  {
    id: 'task-15',
    title: 'Integrar sistema de pagos',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'En Progreso',
    estimatedHours: '9h',
    createdAt: '2026-03-11',
  },
  {
    id: 'task-16',
    title: 'Documentar API REST',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'Backlog',
    estimatedHours: '9h',
    createdAt: '2026-03-09',
  },
  {
    id: 'task-17',
    title: 'Configurar pipeline de CI/CD',
    description: 'Descripcion de la tarea',
    group: 'DevOps Team',
    groupAccent: 'orange',
    assignee: 'Henry Moore',
    assigneeInitials: 'HM',
    status: 'Backlog',
    estimatedHours: '7h',
    createdAt: '2026-03-11',
  },
  {
    id: 'task-18',
    title: 'Optimizar consultas de base de datos',
    description: 'Descripcion de la tarea',
    group: 'DevOps Team',
    groupAccent: 'orange',
    assignee: 'Grace Wilson',
    assigneeInitials: 'GW',
    status: 'Backlog',
    estimatedHours: '15h',
    createdAt: '2026-03-05',
  },
  {
    id: 'task-19',
    title: 'Integrar sistema de pagos',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Alice Johnson',
    assigneeInitials: 'AJ',
    status: 'En Progreso',
    estimatedHours: '12h',
    createdAt: '2026-03-03',
  },
  {
    id: 'task-20',
    title: 'Optimizar consultas de base de datos',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Alice Johnson',
    assigneeInitials: 'AJ',
    status: 'En Progreso',
    estimatedHours: '15h',
    createdAt: '2026-03-07',
  },
  {
    id: 'task-21',
    title: 'Integrar sistema de pagos',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Frank Miller',
    assigneeInitials: 'FM',
    status: 'En Progreso',
    estimatedHours: '8h',
    createdAt: '2026-03-09',
  },
  {
    id: 'task-22',
    title: 'Implementar busqueda avanzada',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Frank Miller',
    assigneeInitials: 'FM',
    status: 'En Progreso',
    estimatedHours: '6h',
    createdAt: '2026-02-24',
  },
  {
    id: 'task-23',
    title: 'Refactorizar codigo legacy',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Alice Johnson',
    assigneeInitials: 'AJ',
    status: 'Completada',
    estimatedHours: '8h',
    createdAt: '2026-03-07',
    completedAt: '2026-03-07',
    actualHours: '7h',
  },
  {
    id: 'task-24',
    title: 'Mejorar rendimiento del frontend',
    description: 'Descripcion de la tarea',
    group: 'Frontend Team',
    groupAccent: 'red',
    assignee: 'Bob Smith',
    assigneeInitials: 'BS',
    status: 'Completada',
    estimatedHours: '17h',
    createdAt: '2026-03-09',
    completedAt: '2026-03-14',
    actualHours: '18h',
  },
  {
    id: 'task-25',
    title: 'Refactorizar codigo legacy',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'Carol White',
    assigneeInitials: 'CW',
    status: 'Completada',
    estimatedHours: '19h',
    createdAt: '2026-03-12',
    completedAt: '2026-03-15',
    actualHours: '9h',
  },
  {
    id: 'task-26',
    title: 'Implementar autenticacion JWT',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'David Brown',
    assigneeInitials: 'DB',
    status: 'Completada',
    estimatedHours: '8h',
    createdAt: '2026-02-22',
    completedAt: '2026-02-27',
    actualHours: '16h',
  },
  {
    id: 'task-27',
    title: 'Configurar pipeline de CI/CD',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'Carol White',
    assigneeInitials: 'CW',
    status: 'Completada',
    estimatedHours: '13h',
    createdAt: '2026-03-03',
    completedAt: '2026-03-07',
    actualHours: '14h',
  },
  {
    id: 'task-28',
    title: 'Configurar pipeline de CI/CD',
    description: 'Descripcion de la tarea',
    group: 'Backend Team',
    groupAccent: 'blue',
    assignee: 'Carol White',
    assigneeInitials: 'CW',
    status: 'Completada',
    estimatedHours: '15h',
    createdAt: '2026-03-07',
    completedAt: '2026-03-12',
    actualHours: '17h',
  },
  {
    id: 'task-29',
    title: 'Crear componentes reutilizables',
    description: 'Descripcion de la tarea',
    group: 'Design Team',
    groupAccent: 'green',
    assignee: 'Emma Davis',
    assigneeInitials: 'ED',
    status: 'Completada',
    estimatedHours: '11h',
    createdAt: '2026-03-08',
    completedAt: '2026-03-08',
    actualHours: '12h',
  },
]
